spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:mysql://localhost:3306/mayuri-local-db
    username: mayuri-local-user
    password: mayuri-local-password
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/mayuri-local-db
    user: mayuri-local-user
    password: mayuri-local-password
    locations: classpath:db/migration
    baseline-version: 1

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URL}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-expired: 3_600_000
    refresh-expired: 1_209_600_000

logging:
  level:
    org.hibernate.SQL: debug