version: '3'

services:
  mysql:
    image: mysql:8.3.0
    container_name: mayuri-mysql8
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: mayuri-local-user
      MYSQL_PASSWORD: mayuri-local-password
      MYSQL_DATABASE: mayuri-local-db
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Seoul'
    volumes:
      - mayuri-local-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7.2.4-alpine
    container_name: mayuri-redis7
    command: redis-server --port 6379
    restart: always
    hostname: root
    labels:
      - 'mode:standalone'
    ports:
      - '6379:6379'

volumes:
  mayuri-local-db: